config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports

  resources :previews
  get '/preview_info', to: 'previews#course_preview'
  post '/charge_course', to: 'previews#create_charge'

  resources :choices
  post '/submit_choices', to: 'choices#submit_choices'
  post '/update_choice', to: 'choices#change_choice'

  resources :questions
  
  resources :quizzes
  post '/quiz_submission', to: 'quizzes#submit_quiz'
  get '/check_user_quiz', to: 'quizzes#check_quiz'

  resources :checkpoints
  get '/get_checkpoints', to: 'checkpoints#get_section_checkpoints'
  post '/mark_checkpoint_complete', to: 'checkpoints#mark_checkpoint_complete'
  get '/check_if_complete', to: 'checkpoints#check_if_complete'
  get '/next_checkpoint', to: 'checkpoints#next_checkpoint'
  post '/sort_checkpoints', to: 'checkpoints#sort'

  resources :sections
  get '/get_section_progress', to: 'sections#get_section_progress'

  resources :courses
  post '/activate', to: 'courses#toggle_activate_course'
  post '/add_course', to: 'courses#create_user_course'
  post '/uc_active', to: 'courses#activate_user_course'
  post '/admin_add_course', to: 'courses#admin_add_course'
  get '/get_courses', to: 'courses#get_courses'
  get '/get_course_progress', to: 'courses#get_course_progress'
  get '/get_course_progress_users', to: 'courses#users_show_course_progress'
  post '/archive_course', to: 'courses#archive'
  get '/archived_courses', to: 'courses#archived_courses'
  
  devise_for :users
  resources :users do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
  delete '/sign_out_user', to: 'dash#sign_out'
  post '/make_admin', to: 'users#make_admin'
  get '/get_user_show_data', to: 'users#get_course_data'

  resources :landing_pages

  get '/dash', to: 'dash#dash'
  get '/where_you_are', to: 'dash#where_you_are'
  get '/sections_and_checkpoints', to: 'dash#get_s_and_c'
  get '/new_students', to: 'dash#get_new_students'
  get '/get_new_guests', to: 'dash#get_new_guests'
  get '/get_monthly_revenue', to: 'dash#monthly_revenue'
  get '/get_admin_dash_graph_data', to: 'dash#get_graph_data'

  root to: 'landing_pages#index'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  require 'quiz_logic'
  include QuizLogic
  require 'course_overview_logic'
  include CourseOverviewLogic
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    if current_user.admin?
      @q = Quiz.ransack(params[:q])
      @quizzes = @q.result.includes(:questions, :section).paginate(page: params[:page])
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    authorize @quiz
    @complete_quiz = serve_complete_quiz_sorted(@quiz)
    @section = @quiz.section
    @course = @quiz.section.course
    @next_checkpoint = get_next_checkpoint(@quiz)
    puts @next_checkpoint.to_json
  end

  # GET /quizzes/new
  def new
    authorize @quiz
    if current_user.admin?
      @quiz = Quiz.new
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /quizzes/1/edit
  def edit
    authorize @quiz
    if current_user.guest? || current_user.student?
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    authorize @quiz
    respond_to do |format|
      if @quiz.save
        format.html { redirect_to new_question_path, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    authorize @quiz
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    authorize @quiz
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def submit_quiz
    puts params[:answers]
    quiz = Quiz.find(params[:quiz])
    selections = eval(params[:answers])
    results = score_quiz(quiz, selections, current_user)
    render json: results.to_json, status: :ok
  end

  def check_quiz
    user = User.find(params[:user_id])
    user_quiz = UserQuiz.where(user_id: user.id, quiz_id: params[:quiz_id]).last
    quiz = Quiz.includes(:questions).find(params[:quiz_id])
    questions = quiz.questions
    temp = UserQuestion.where(question: questions, user: user)
    user_questions =  temp.map { |x| x if x.created_at == temp.select { |y| y.question ==  x.question }.map(&:created_at).max }.compact
    return_hash = format_user_quiz(user_questions, user_quiz)
    render json: return_hash.to_json, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:section_id, :title, :order_number, :time_to_complete, :description)
    end

    def get_next_checkpoint(quiz)
      checkpoints = aggregate_checkpoints_and_quizzes(quiz.section.id, current_user)
      next_number = quiz.order_number + 1
      next_checkpoint = checkpoints.find { |c| c[:order_number] == next_number }
      if next_checkpoint.present?
        if next_checkpoint[:type] == 'quiz'
          next_checkpoint = {is_a: 'qu', id: next_checkpoint[:id] }
        else
          next_checkpoint = {is_a: 'ch', id: next_checkpoint[:id] }
        end
      else
        next_checkpoint = 'last'
      end
      return next_checkpoint
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<div class="card" id="show-form-card">
  <div class="card-header" style='background-color: #3b3a39; color: whitesmoke;'>
    Quiz
  </div>
  <div class="card-body">
    <%= form_with(model: quiz, local: true) do |form| %>
      <% if quiz.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

          <ul>
            <% quiz.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :section_id %>
        <%= form.collection_select :section_id, Section.order(:name), :id, :name, include_blank: true, input_html: { id: "drop" } %>
      </div>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :order_number %>
        <%= form.number_field :order_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :time_to_complete %>
        <%= form.number_field :time_to_complete, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.button :submit, class: "btn btn-outline-success pull-right"%>
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/edit.html.erb
<%= render 'form', quiz: @quiz %>

app/views/quizzes/index.html.erb
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="panel panel-primary filterable">
                        <div class="panel-heading">
                            <h3 class="panel-title">Quizzes</h3>
                        </div>
                        <table class="table">
                            <thead>
                                <tr class="filters">
                                    <%= search_form_for @q do |f| %>
                                        <th><%= f.search_field :id_eq, class: "form-control", placeholder: "ID" %></th>
                                        <th><%= f.search_field :order_number_eq, class: "form-control", placeholder: "Order Number" %></th>
                                        <th><%= f.search_field :title_cont, class: "form-control", placeholder: "Title" %></th>
                                        <th><%= f.search_field :description_cont, class: "form-control", placeholder: "Description" %></th>
                                        <th><%= f.search_field :questions_question_cont, class: "form-control", placeholder: "Questions" %></th>
                                        <th><%= f.search_field :section_name_start, class: "form-control", placeholder: "Section" %></th>
                                        <th><%= f.submit class: "btn btn-primary float-right" %></th>
                                    <% end %>
                                </tr>
                            </thead>
                            <tbody>
                                <% @quizzes.each do |quiz| %>
                                <tr>
                                    <td><%= quiz.id %></td>
                                    <td><%= quiz.order_number %></td>
                                    <td><%= quiz.title %></td>
                                    <td><small><%= quiz.description %></small></td>
                                    <td>
                                        <% quiz.questions.order(:order_number).each do |q| %>
                                            <small><%= q.order_number %>. <%= link_to q.question, edit_question_path(q) %></small>
                                        <% end %>
                                    </td>
                                    <td>Course: <%= link_to quiz.section.course.title, course_path(quiz.section.course) %> <br> Section: <%= link_to quiz.section.name, course_path(quiz.section.course) %></td>
                                    <td><%= link_to 'Show', quiz_path(quiz), class: 'btn btn-primary btn-sm' %> <br> <%= link_to 'Edit', edit_quiz_path(quiz), class: 'btn btn-primary btn-sm' %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <%= will_paginate @quizzes %>
    </div>
</div>

app/views/quizzes/new.html.erb
<%= render 'form', quiz: @quiz %>

app/views/quizzes/show.html.erb
<%= tag.div id: "quizzesShow", data: { quiz: @complete_quiz.to_json, sect: @section.to_json, cour: @course.to_json, cu: current_user.to_json, nc: @next_checkpoint.to_json } %>