config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports

  resources :previews
  get '/preview_info', to: 'previews#course_preview'
  post '/charge_course', to: 'previews#create_charge'

  resources :choices
  post '/submit_choices', to: 'choices#submit_choices'
  post '/update_choice', to: 'choices#change_choice'

  resources :questions
  
  resources :quizzes
  post '/quiz_submission', to: 'quizzes#submit_quiz'
  get '/check_user_quiz', to: 'quizzes#check_quiz'

  resources :checkpoints
  get '/get_checkpoints', to: 'checkpoints#get_section_checkpoints'
  post '/mark_checkpoint_complete', to: 'checkpoints#mark_checkpoint_complete'
  get '/check_if_complete', to: 'checkpoints#check_if_complete'
  get '/next_checkpoint', to: 'checkpoints#next_checkpoint'
  post '/sort_checkpoints', to: 'checkpoints#sort'

  resources :sections
  get '/get_section_progress', to: 'sections#get_section_progress'

  resources :courses
  post '/activate', to: 'courses#toggle_activate_course'
  post '/add_course', to: 'courses#create_user_course'
  post '/uc_active', to: 'courses#activate_user_course'
  post '/admin_add_course', to: 'courses#admin_add_course'
  get '/get_courses', to: 'courses#get_courses'
  get '/get_course_progress', to: 'courses#get_course_progress'
  get '/get_course_progress_users', to: 'courses#users_show_course_progress'
  post '/archive_course', to: 'courses#archive'
  get '/archived_courses', to: 'courses#archived_courses'
  
  devise_for :users
  resources :users do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
  delete '/sign_out_user', to: 'dash#sign_out'
  post '/make_admin', to: 'users#make_admin'
  get '/get_user_show_data', to: 'users#get_course_data'

  resources :landing_pages

  get '/dash', to: 'dash#dash'
  get '/where_you_are', to: 'dash#where_you_are'
  get '/sections_and_checkpoints', to: 'dash#get_s_and_c'
  get '/new_students', to: 'dash#get_new_students'
  get '/get_new_guests', to: 'dash#get_new_guests'
  get '/get_monthly_revenue', to: 'dash#monthly_revenue'
  get '/get_admin_dash_graph_data', to: 'dash#get_graph_data'

  root to: 'landing_pages#index'
end

app/models/choice.rb
# == Schema Information
#
# Table name: choices
#
#  id          :bigint           not null, primary key
#  choice      :string
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :bigint           not null
#
# Indexes
#
#  index_choices_on_question_id  (question_id)
#
# Foreign Keys
#
#  fk_rails_...  (question_id => questions.id)
#

class Choice < ApplicationRecord
  belongs_to :question, dependent: :destroy
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  require 'quiz_logic'
  include QuizLogic
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    if current_user.admin?
      @choices = Choice.all
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
    authorize @choice
  end

  # GET /choices/new
  def new
    if current_user.admin?
      @choice = Choice.new
      @questions = Question.all
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /choices/1/edit
  def edit
    authorize @choice
    if current_user.student? || current_user.guest
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)
    authorize @choice
    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  def submit_choices
    question = Question.find(params[:question_id])
    quiz = question.quiz
    if sort_and_save_question_choices(question, params[:choices])
      redirect_to quiz
    else
      render :new
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    authorize @choice
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    authorize @choice
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_choice
    choice = Choice.find(params[:id])
    choice.choice = params[:choice]
    if choice.save!
      render json: "good".to_json, status: :ok
    else
      render json: "no good".to_json, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:question_id, :choice, :number)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_with(model: choice, local: true) do |form| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
        <% choice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :choice %>
    <%= form.text_field :choice %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Choice</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.question_id %></td>
        <td><%= choice.choice %></td>
        <td><%= choice.number %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<% if user_signed_in? && current_user.admin? %>
    <%= tag.div id:"choiceForm", data: { qu: @questions.to_json } %>
<% end %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @choice.question_id %>
</p>

<p>
  <strong>Choice:</strong>
  <%= @choice.choice %>
</p>

<p>
  <strong>Number:</strong>
  <%= @choice.number %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>