config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports

  resources :previews
  get '/preview_info', to: 'previews#course_preview'
  post '/charge_course', to: 'previews#create_charge'

  resources :choices
  post '/submit_choices', to: 'choices#submit_choices'
  post '/update_choice', to: 'choices#change_choice'

  resources :questions
  
  resources :quizzes
  post '/quiz_submission', to: 'quizzes#submit_quiz'
  get '/check_user_quiz', to: 'quizzes#check_quiz'

  resources :checkpoints
  get '/get_checkpoints', to: 'checkpoints#get_section_checkpoints'
  post '/mark_checkpoint_complete', to: 'checkpoints#mark_checkpoint_complete'
  get '/check_if_complete', to: 'checkpoints#check_if_complete'
  get '/next_checkpoint', to: 'checkpoints#next_checkpoint'
  post '/sort_checkpoints', to: 'checkpoints#sort'

  resources :sections
  get '/get_section_progress', to: 'sections#get_section_progress'

  resources :courses
  post '/activate', to: 'courses#toggle_activate_course'
  post '/add_course', to: 'courses#create_user_course'
  post '/uc_active', to: 'courses#activate_user_course'
  post '/admin_add_course', to: 'courses#admin_add_course'
  get '/get_courses', to: 'courses#get_courses'
  get '/get_course_progress', to: 'courses#get_course_progress'
  get '/get_course_progress_users', to: 'courses#users_show_course_progress'
  post '/archive_course', to: 'courses#archive'
  get '/archived_courses', to: 'courses#archived_courses'
  
  devise_for :users
  resources :users do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
  delete '/sign_out_user', to: 'dash#sign_out'
  post '/make_admin', to: 'users#make_admin'
  get '/get_user_show_data', to: 'users#get_course_data'

  resources :landing_pages

  get '/dash', to: 'dash#dash'
  get '/where_you_are', to: 'dash#where_you_are'
  get '/sections_and_checkpoints', to: 'dash#get_s_and_c'
  get '/new_students', to: 'dash#get_new_students'
  get '/get_new_guests', to: 'dash#get_new_guests'
  get '/get_monthly_revenue', to: 'dash#monthly_revenue'
  get '/get_admin_dash_graph_data', to: 'dash#get_graph_data'

  root to: 'landing_pages#index'
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  require 'stripe'
  require 'new_course_logic'
  include NewCourseLogic
  before_action :set_preview, only: [:show, :edit, :update, :destroy]

  # GET /previews
  # GET /previews.json
  def index
    if current_user.admin?
      @previews = Preview.all
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /previews/1
  # GET /previews/1.json
  def show
    @course = @preview.course
    @sections = @course.sections
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "#{@course.title}",
      amount: @course.price * 100
    }
  end

  # GET /previews/new
  def new
    if current_user.admin?
      @preview = Preview.new
    else
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # GET /previews/1/edit
  def edit
    if current_user.guest? || current_user.student?
      redirect_to root_path
      flash[:notice] = "Whoops! You're not supposed to be there!"
    end
  end

  # POST /previews
  # POST /previews.json
  def create
    @preview = Preview.new(preview_params)

    respond_to do |format|
      if @preview.save
        format.html { redirect_to @preview, notice: 'Preview was successfully created.' }
        format.json { render :show, status: :created, location: @preview }
      else
        format.html { render :new }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  def course_preview
    course = Course.includes(:preview).find(params[:id])
    if course.preview.present?
      render json: course.preview.to_json, status: :ok
    else
      render json: nil.to_json, status: :ok
    end
  end

  # PATCH/PUT /previews/1
  # PATCH/PUT /previews/1.json
  def update
    respond_to do |format|
      if @preview.update(preview_params)
        format.html { redirect_to @preview, notice: 'Preview was successfully updated.' }
        format.json { render :show, status: :ok, location: @preview }
      else
        format.html { render :edit }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previews/1
  # DELETE /previews/1.json
  def destroy
    @preview.destroy
    respond_to do |format|
      format.html { redirect_to previews_url, notice: 'Preview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_charge
    @preview = Preview.find(params[:preview_id])
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
  
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: configure_price(@preview.course),
      description: "#{@preview.course.title} enrollment - #{current_user.email}",
      currency: 'usd'
    )

    create_new_user_course(@preview.course.id, current_user)
    flash[:notice] = "Thanks for enrolling! #{current_user.email}!"
    redirect_to @preview.course # or wherever
  
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preview
      @preview = Preview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preview_params
      params.require(:preview).permit(:course_id, :blurb, :pitch, :image)
    end

    def configure_price(course)
      indx = course.price.to_s.split('').index('.') + 1
      length = course.price.to_s.split('').count
      if length - indx == 1
        return course.price.to_s.gsub('.', '').to_i * 10
      elsif length - indx == 2
        return course.price.to_s.gsub('.', '').to_i
      end
    end
end

app/helpers/previews_helper.rb
module PreviewsHelper
end

app/views/previews/_form.html.erb
<div class="card" id="show-form-card">
  <div class="card-header" style='background-color: #3b3a39; color: whitesmoke;'>
    Preview
  </div>
  <div class="card-body">
    <%= form_with(model: preview, local: true) do |form| %>
      <% if preview.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(preview.errors.count, "error") %> prohibited this checkpoint from being saved:</h2>

          <ul>
            <% preview.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :course_id %><br />
        <%= form.collection_select :course_id, Course.order(:title), :id, :title, include_blank: true, input_html: { id: "drop" } %>
      </div>

      <div class="form-group">
        <%= form.label :blurb, "Blurb: A quick intro to what the course is" %>
        <%= form.text_area :blurb, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :pitch, "Pitch, your chance to sell the course, please don't drop images here" %>
        <%= form.rich_text_area :pitch %>
      </div>

      <div class="form-group">
        <%= form.label :image, "Image: this will be an image that goes next to your pitch for visual flare." %><br>
        <%= form.file_field :image %>
      </div>

      <div class="actions">
        <%= form.button :submit, class: "btn btn-outline-success pull-right"%>
      </div>
    <% end %>
  </div>
</div>

app/views/previews/edit.html.erb
<h1>Editing Preview</h1>

<%= render 'form', preview: @preview %>

<%= link_to 'Show', @preview %> |
<%= link_to 'Back', previews_path %>

app/views/previews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Previews</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Blurb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @previews.each do |preview| %>
      <tr>
        <td><%= preview.course_id %></td>
        <td><%= preview.blurb %></td>
        <td><%= link_to 'Show', preview %></td>
        <td><%= link_to 'Edit', edit_preview_path(preview) %></td>
        <td><%= link_to 'Destroy', preview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preview', new_preview_path %>

app/views/previews/new.html.erb
<%= render 'form', preview: @preview %>

app/views/previews/show.html.erb
<div class="container-fluid content-row">
  <div class="row" id="cf-lcop">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-10">
      <div class="preview">
        <h1 class="display-3 lpreview"><%= @course.title %></h1>
        <h4 class="lead lpreview"><%= @preview.blurb %></h4>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
  </div>
</div>
<br>
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-md-6">
      <%= @preview.pitch %>
    </div>
    <div class="col-md-4">
      <br />
      <div class="card">
        <%= image_tag @preview.image.variant(resize_to_limit: [500, 500]), class: "card-img-top" %>
        <div class="card-body">
          <div class="row">
            <div class="col">
              <p class="card-text">Price: $<%= @course.price %></p>
              <p class="card-text">Accreditation: <%= @course.accreditation %></p>
              <p class="card-text">Duration: <%= @course.duration %> months</p>
              <p class="card-text"><%= @course.users.count %> already enrolled!</p>
            </div>
            <div class="col">
                <% if current_user.courses.exclude?(@preview.course) %>
                  <%= form_tag charge_course_path do %>
                    <%= hidden_field_tag(:preview_id, @preview.id) %>
                    <h5>Enroll Now!</h5>
                    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-md-10 text-center">
      <hr>
      <h2 class="display-4">There are <%= @sections.count %> sections in this course</h2>
    </div>
  </div>
  <% @sections.each do |s| %>
    <div class="row">
      <div class="col-lg-1">
      </div>
      <div class="col-md-1 justify-content-center">
        <p style="margin-bottom:2px;margin-top:20px;text-align:center;">Section</p>
        <h1 class="display-4 numbering"><%= s.order_number %></h1>
      </div>
      <div class="col-md-9 text-left">
        <div class="row">
          <div class="col">
            <h3 class="display-6" style="margin-bottom:5px;"><%= s.name %></h2>
            <small><p style="margin-bottom:5px;"><%= s.checkpoints.count + s.quizzes.count %> Checkpoints</p></small>
          </div>
        </div>
        <hr>
        <p><%= s.description %></p>
      </div>
      <br>
      <hr>
    <div class="col-lg-1">
    </div>
    </div>
  <% end %>
<div>